# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79528a9cb3ee42631222cbdc444d94e98024954f7a21cfa8394c58862a74fb7b80b614f26248e3a42160e6c077fde51c9ace53631f669546e7176fc8360f229

test:
  secret_key_base: a1ce074ac63fd627e79550eb4fe2240570ffbf44625e877f801b40d5c2bf91b72fe943e4060df5f827dedf6d68a61c8fbd4e35a8b9b5d60ad8b623277740f2bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
